insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Tammie', 'Howchin', '91266 Forest Dale Circle', 'Miami', 'FL', 'F', '1968-12-16 16:29:59');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Roxana', 'Turfus', '85336 Trailsway Crossing', 'Portland', 'OR', 'F', '1999-11-01 19:59:56');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Devlin', 'Sedgefield', '9 Wayridge Point', 'Atlanta', 'GA', 'M', '1950-11-21 06:49:36');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Ethyl', 'Artus', '0204 Lien Avenue', 'Provo', 'UT', 'F', '1969-09-21 21:50:31');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Clarissa', 'Keigher', '761 Barnett Circle', 'Washington', 'DC', 'F', '1968-06-29 06:29:33');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Mariana', 'Callen', '7 Quincy Place', 'Boston', 'MA', 'M', '1941-08-15 20:08:04');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Twila', 'MacCombe', '062 Corben Parkway', 'Naples', 'FL', 'F', '1945-09-26 12:39:43');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Georgy', 'Kittredge', '0 Center Place', 'Aurora', 'CO', 'M', '1952-04-11 10:31:40');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Clarice', 'Chessill', '64748 Towne Avenue', 'Lees Summit', 'MO', 'M', '1970-09-05 23:02:24');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Odelia', 'Danhel', '6 Iowa Street', 'Minneapolis', 'MN', 'F', '1943-11-08 05:40:19');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Alaine', 'Ascrofte', '52 Del Sol Point', 'Lubbock', 'TX', 'M', '2017-02-21 04:27:44');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Filmer', 'Kubacek', '8 Fulton Crossing', 'Fort Worth', 'TX', 'M', '2008-08-10 08:58:51');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Delaney', 'Neagle', '22882 Rieder Drive', 'Philadelphia', 'PA', 'F', '2017-03-31 17:21:51');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Lukas', 'O'' Donohue', '9 Blaine Terrace', 'Conroe', 'TX', 'M', '1981-09-02 09:46:14');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Courtney', 'Bottrill', '337 Hallows Hill', 'Johnstown', 'PA', 'F', '1947-02-07 06:12:07');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Anastasia', 'Callinan', '8961 Eastwood Junction', 'Lynn', 'MA', 'M', '1940-08-04 15:58:02');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Ophelia', 'Ashforth', '8919 Clyde Gallagher Junction', 'Roanoke', 'VA', 'M', '1963-12-24 13:40:16');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Kippie', 'Genese', '59522 Village Green Parkway', 'Charlotte', 'NC', 'M', '1995-02-17 02:51:51');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Cathee', 'Pennino', '1312 Dottie Place', 'Berkeley', 'CA', 'M', '1999-05-03 11:51:54');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Dylan', 'Senecaux', '0682 Cambridge Center', 'Erie', 'PA', 'M', '1955-01-11 01:10:00');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Fields', 'Elix', '146 Arizona Lane', 'New Haven', 'CT', 'F', '1959-11-15 18:48:38');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Claudius', 'Andrichak', '0600 Hagan Hill', 'Cleveland', 'OH', 'F', '2019-04-26 15:58:27');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Fenelia', 'Roskruge', '09 Center Court', 'Nashville', 'TN', 'F', '1950-06-08 01:04:25');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Tamqrah', 'Fateley', '870 Bashford Junction', 'Buffalo', 'NY', 'M', '1977-06-27 08:39:36');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Ciro', 'Billingham', '1797 Huxley Court', 'Colorado Springs', 'CO', 'F', '1967-11-16 23:27:21');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Zebulen', 'Ayllett', '25 Holmberg Drive', 'Sioux Falls', 'SD', 'F', '1962-01-28 07:39:30');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Aurora', 'Jobbings', '43010 Schiller Way', 'North Hollywood', 'CA', 'M', '1967-08-05 16:06:13');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Tina', 'Tremellier', '9219 Continental Crossing', 'Fort Pierce', 'FL', 'M', '1986-09-22 15:13:26');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Levi', 'Grote', '5 Sage Terrace', 'Madison', 'WI', 'M', '1980-01-05 15:44:28');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Lucky', 'Stephens', '394 Elmside Crossing', 'Jacksonville', 'FL', 'F', '1968-04-23 12:52:17');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Corrianne', 'O''Fergus', '2 Mifflin Plaza', 'Fort Worth', 'TX', 'M', '1980-11-02 02:17:17');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Marigold', 'Petry', '362 Mallard Lane', 'Fort Worth', 'TX', 'M', '2009-11-23 18:36:53');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Nicoline', 'Rasmus', '512 Gina Alley', 'Seattle', 'WA', 'M', '1987-11-09 17:26:03');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Riccardo', 'Slora', '6 Hanover Circle', 'Tulsa', 'OK', 'F', '2012-07-14 03:02:30');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Damiano', 'Gerring', '13486 Brown Court', 'Baltimore', 'MD', 'M', '1994-02-15 00:11:09');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Bianka', 'McGrann', '19158 Schiller Park', 'Houston', 'TX', 'M', '2010-01-29 17:46:31');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Halli', 'Colgrave', '0 Maywood Parkway', 'Charlotte', 'NC', 'M', '1971-03-02 23:21:20');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Chicky', 'McErlaine', '6 Northwestern Park', 'Anchorage', 'AK', 'F', '1940-05-18 07:49:38');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Gal', 'Frostick', '339 Comanche Terrace', 'Sacramento', 'CA', 'F', '1951-11-01 14:41:15');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Elise', 'Costall', '993 Di Loreto Hill', 'Tucson', 'AZ', 'F', '1969-03-04 14:14:00');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Tandy', 'Amber', '651 Del Sol Road', 'Detroit', 'MI', 'F', '1945-11-02 01:57:43');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Robinett', 'Edeler', '7249 Eliot Parkway', 'Columbia', 'SC', 'M', '1997-02-18 15:55:31');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Lanae', 'Novis', '11 Vermont Drive', 'Cincinnati', 'OH', 'F', '1945-09-21 22:47:53');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Nat', 'Pulman', '47232 2nd Court', 'Fort Wayne', 'IN', 'M', '1987-08-17 07:51:41');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Marley', 'Browncey', '27552 Grover Hill', 'Minneapolis', 'MN', 'F', '2014-09-24 14:29:08');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Scot', 'Cowtherd', '21 Union Place', 'Philadelphia', 'PA', 'M', '2011-09-13 14:01:10');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Xavier', 'Shingler', '061 Hermina Street', 'Saint Paul', 'MN', 'M', '1968-08-11 03:24:33');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Vernor', 'Bradforth', '7 Maywood Court', 'Dallas', 'TX', 'F', '1978-10-20 03:11:48');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Shela', 'Le Marquand', '5005 Springview Place', 'Lexington', 'KY', 'F', '1942-08-23 04:12:39');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Nye', 'Reuss', '87817 Brentwood Crossing', 'Columbia', 'SC', 'F', '2019-04-22 19:52:51');

