insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Drusy', 'Garces', '232 Bultman Terrace', 'Roanoke', 'VA', 'M', '2010-09-18 01:58:25');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Vitoria', 'Thormwell', '9461 Crescent Oaks Trail', 'Richmond', 'VA', 'F', '1949-09-13 04:13:09');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Adrienne', 'McInnerny', '7043 Manufacturers Parkway', 'Santa Rosa', 'CA', 'M', '1968-10-10 04:44:22');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Lexie', 'Iorizzi', '55 4th Court', 'Fullerton', 'CA', 'M', '1996-03-25 00:07:04');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Corri', 'Geelan', '9 Sugar Avenue', 'Clearwater', 'FL', 'F', '1995-05-21 19:45:40');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Tobias', 'Cutteridge', '1965 Macpherson Terrace', 'Wilmington', 'DE', 'F', '1988-04-20 07:58:18');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Willamina', 'Ales0', '74527 Kennedy Court', 'Des Moines', 'IA', 'M', '1984-03-04 19:02:40');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Bethany', 'Crates', '295 Harbort Crossing', 'Washington', 'DC', 'M', '1959-11-22 04:19:46');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Shirline', 'Myring', '1498 American Ash Trail', 'Bronx', 'NY', 'M', '1979-05-21 20:05:22');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Ricard', 'Rollett', '86 Annamark Place', 'New York City', 'NY', 'F', '1994-04-13 12:05:07');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Siegfried', 'Pebworth', '9 Heath Trail', 'Tacoma', 'WA', 'F', '1941-11-10 11:21:19');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Christal', 'Stean', '758 Arizona Road', 'Merrifield', 'VA', 'F', '1992-05-03 18:37:48');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Florentia', 'Mackriell', '25989 Maryland Center', 'Baton Rouge', 'LA', 'M', '1969-09-07 22:25:37');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Nonnah', 'Dalyell', '9885 Crescent Oaks Pass', 'Joliet', 'IL', 'M', '2007-12-11 03:43:04');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Fidole', 'Van der Velden', '06674 Vernon Terrace', 'Jacksonville', 'FL', 'F', '1961-08-25 14:11:10');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Avigdor', 'Bennetto', '100 North Parkway', 'Metairie', 'LA', 'F', '1994-10-22 01:21:09');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Menard', 'Tant', '0 Waubesa Drive', 'Fort Smith', 'AR', 'F', '1958-09-24 04:20:15');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Barbabra', 'Sturdy', '036 Glendale Point', 'Raleigh', 'NC', 'F', '1947-06-22 23:48:03');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Reube', 'Danovich', '7 Buhler Place', 'Lexington', 'KY', 'F', '2009-01-20 12:08:49');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Christie', 'Cuddehy', '76871 High Crossing Parkway', 'Warren', 'OH', 'M', '1968-06-24 11:10:07');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Trula', 'Sichardt', '18 Fuller Terrace', 'New York City', 'NY', 'F', '1960-03-12 10:23:51');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Alisun', 'Headford', '3766 Anthes Lane', 'High Point', 'NC', 'F', '1949-11-02 15:02:37');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Rodge', 'Estcot', '5980 Arapahoe Junction', 'Jacksonville', 'FL', 'M', '1953-07-11 03:21:41');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Weber', 'Domingues', '8750 Farragut Trail', 'Grand Forks', 'ND', 'F', '1989-08-24 11:49:00');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Bearnard', 'Muris', '73255 Little Fleur Hill', 'Las Vegas', 'NV', 'M', '1957-11-20 18:03:34');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Basia', 'Andreopolos', '83 Parkside Drive', 'Saint Louis', 'MO', 'F', '1974-07-02 20:28:20');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Dudley', 'Akroyd', '117 Glacier Hill Alley', 'Erie', 'PA', 'F', '2007-01-16 08:17:44');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Felicia', 'Stealy', '00915 Forest Terrace', 'Inglewood', 'CA', 'M', '1995-08-10 17:23:47');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Hertha', 'Kingsnode', '94 Birchwood Trail', 'Jamaica', 'NY', 'M', '2007-11-29 09:37:32');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Sergent', 'Giacobbo', '8940 Morning Place', 'Miami Beach', 'FL', 'M', '1975-04-17 23:50:23');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Ruby', 'Marchent', '73 Ruskin Center', 'Columbus', 'GA', 'F', '1990-08-11 07:12:37');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Winnie', 'Delouch', '8779 Daystar Parkway', 'San Francisco', 'CA', 'F', '1961-07-01 21:03:24');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Gretel', 'Cocking', '6566 Monica Center', 'Atlanta', 'GA', 'F', '2008-05-28 15:57:55');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Taffy', 'Hindge', '259 Hooker Alley', 'Richmond', 'VA', 'F', '1955-11-20 11:48:36');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Lorettalorna', 'Botting', '4 Spohn Terrace', 'Tampa', 'FL', 'M', '1945-12-03 06:21:23');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Elmo', 'Rosberg', '43434 Manley Alley', 'Memphis', 'TN', 'F', '1976-01-22 08:54:23');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Martelle', 'Maydway', '74747 Calypso Circle', 'Baltimore', 'MD', 'F', '1994-04-20 12:43:08');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Reinaldos', 'Kingcote', '84841 Grover Trail', 'Roanoke', 'VA', 'M', '1989-12-28 23:40:20');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Sinclair', 'Maidstone', '170 Sunfield Crossing', 'Louisville', 'KY', 'M', '1980-11-11 04:00:17');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Sophronia', 'Powe', '12 Helena Circle', 'Orlando', 'FL', 'F', '1951-02-25 20:22:01');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Alfons', 'Duckinfield', '30473 Bultman Road', 'New Orleans', 'LA', 'F', '1975-07-21 06:28:50');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Agata', 'Alu', '50 Stoughton Court', 'New Orleans', 'LA', 'F', '2010-12-30 18:37:58');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Nelli', 'Picopp', '33791 Columbus Place', 'Rochester', 'NY', 'F', '1969-12-09 03:20:34');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Morten', 'Gorch', '44 Debs Circle', 'Harrisburg', 'PA', 'M', '1995-05-31 02:22:44');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Ibbie', 'Potapczuk', '04189 Dovetail Avenue', 'Huntington', 'WV', 'M', '1986-02-10 21:06:11');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Juline', 'Colbran', '294 Cottonwood Park', 'Monroe', 'LA', 'M', '1970-09-04 22:51:59');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Wallas', 'Byrde', '284 Stoughton Way', 'Orlando', 'FL', 'F', '1993-12-11 07:15:33');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Sandye', 'Mintrim', '47 Northfield Avenue', 'Fort Worth', 'TX', 'F', '1961-03-08 13:46:11');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Lark', 'Broster', '28 Steensland Way', 'Saint Louis', 'MO', 'M', '1955-11-18 08:56:33');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Tyrone', 'Maffeo', '23458 Vera Drive', 'Saint Paul', 'MN', 'F', '1979-01-02 08:42:28');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Ofella', 'Sangster', '56 Larry Drive', 'Trenton', 'NJ', 'M', '1966-08-04 20:51:02');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Camella', 'Derges', '7677 Miller Pass', 'Asheville', 'NC', 'M', '1978-12-19 08:46:56');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Candida', 'Ellesmere', '682 Stone Corner Court', 'Ocala', 'FL', 'F', '2001-04-16 15:39:23');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Eran', 'Wiltsher', '63749 Holy Cross Road', 'Erie', 'PA', 'M', '1961-04-15 08:02:38');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Cristian', 'Ply', '520 Tomscot Lane', 'Phoenix', 'AZ', 'M', '1944-10-12 21:26:31');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Lance', 'Laidlaw', '8 Emmet Junction', 'Dallas', 'TX', 'M', '2010-05-13 10:01:07');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Susette', 'Skipping', '30 Packers Avenue', 'Concord', 'CA', 'M', '2003-01-06 00:07:25');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Verge', 'Garvie', '21222 Oriole Trail', 'Chicago', 'IL', 'M', '1960-09-23 23:57:07');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Ivie', 'Waples', '535 Stoughton Avenue', 'San Antonio', 'TX', 'F', '1988-06-26 12:14:11');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Stepha', 'Rowsell', '8 Artisan Plaza', 'Elizabeth', 'NJ', 'F', '1941-10-23 00:37:13');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Mathian', 'Moultrie', '78 Helena Crossing', 'Norcross', 'GA', 'M', '1987-07-17 08:26:06');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Maribelle', 'Rosekilly', '771 Graceland Way', 'Richmond', 'VA', 'M', '1996-06-02 00:04:31');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Dido', 'Gheerhaert', '9 Forster Place', 'Evansville', 'IN', 'M', '1991-10-03 21:18:35');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Nettie', 'Cator', '443 Dennis Way', 'Monroe', 'LA', 'F', '1983-07-01 11:00:04');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Penn', 'Cantwell', '0644 Upham Way', 'Pensacola', 'FL', 'M', '1967-10-19 14:48:38');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Rochella', 'Peake', '0633 Oakridge Court', 'Brooklyn', 'NY', 'F', '1941-12-04 08:19:46');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Asia', 'Demkowicz', '6 Alpine Lane', 'Springfield', 'IL', 'M', '1981-04-19 05:50:41');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Paulette', 'Siddon', '45 Ridge Oak Way', 'Syracuse', 'NY', 'M', '1979-11-25 11:43:38');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Edgard', 'Luther', '69 Schiller Alley', 'Rochester', 'NY', 'M', '1966-03-25 16:59:23');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Cristian', 'Birchwood', '5 Lunder Center', 'San Bernardino', 'CA', 'F', '1951-10-08 04:16:50');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Merralee', 'Mateuszczyk', '20 Anniversary Pass', 'New Haven', 'CT', 'M', '2005-09-17 03:08:12');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Russ', 'Jacklings', '0 Armistice Terrace', 'Oakland', 'CA', 'M', '1988-02-18 11:04:22');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Sacha', 'Janowski', '43587 Gateway Street', 'El Paso', 'TX', 'F', '1965-04-07 05:48:04');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Jerrilyn', 'Darragh', '050 Lakewood Gardens Drive', 'Washington', 'DC', 'M', '1962-12-11 14:55:14');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Corette', 'Lamort', '75 Riverside Hill', 'Glendale', 'CA', 'M', '2000-02-18 22:24:45');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Lenora', 'Geater', '68 La Follette Park', 'New Orleans', 'LA', 'F', '1991-05-21 20:56:08');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Noam', 'Penvarden', '1398 Sloan Road', 'Pittsburgh', 'PA', 'F', '1946-03-17 16:37:30');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Woodie', 'Cosyns', '1814 Crest Line Alley', 'Fairbanks', 'AK', 'F', '1962-02-11 19:26:17');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Pavel', 'Loveman', '78265 Delladonna Center', 'San Antonio', 'TX', 'M', '2004-09-18 15:15:07');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Clem', 'Schlagman', '00 Grover Parkway', 'Wilmington', 'DE', 'F', '1960-05-29 22:23:50');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Essa', 'Collings', '9 5th Parkway', 'El Paso', 'TX', 'M', '1957-06-07 22:58:59');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Pauli', 'Hatherley', '39723 Utah Drive', 'Chicago', 'IL', 'M', '1981-04-10 00:16:13');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Burk', 'Boyles', '42 Farwell Park', 'Cedar Rapids', 'IA', 'F', '1995-07-26 17:51:02');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Tally', 'Darracott', '9170 Clarendon Drive', 'Washington', 'DC', 'M', '1964-11-17 08:55:37');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Addi', 'FitzAlan', '09 Esch Terrace', 'Davenport', 'IA', 'M', '2001-06-27 04:30:34');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Jay', 'Brazener', '415 Ryan Hill', 'Staten Island', 'NY', 'M', '1993-05-28 12:06:11');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Luella', 'Tampion', '6 Maple Wood Road', 'Seattle', 'WA', 'F', '1996-08-27 22:41:20');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Ilsa', 'Berns', '10 Red Cloud Junction', 'Naples', 'FL', 'M', '1965-10-28 12:51:18');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Chiquia', 'Gaukrodge', '1824 Nancy Center', 'Mesa', 'AZ', 'M', '1941-06-30 00:39:21');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Denni', 'Stannas', '359 Portage Pass', 'Jersey City', 'NJ', 'F', '2008-11-24 14:59:19');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Rene', 'Van', '300 Manley Plaza', 'New York City', 'NY', 'F', '1954-07-07 03:07:01');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Nester', 'Cobb', '6 Esker Parkway', 'Joliet', 'IL', 'M', '1944-09-30 12:34:23');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Rosalind', 'Lawlee', '1325 Mayer Lane', 'Tampa', 'FL', 'F', '2002-01-30 16:30:42');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Gray', 'Spikings', '6182 Clemons Parkway', 'Washington', 'DC', 'F', '1983-09-28 03:04:38');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Georgianna', 'Brounsell', '3966 Karstens Drive', 'Louisville', 'KY', 'M', '1943-05-05 07:50:02');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Corny', 'Danovich', '0879 School Point', 'Macon', 'GA', 'M', '1955-05-22 16:51:42');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Florida', 'Lardnar', '2 Atwood Trail', 'Irving', 'TX', 'M', '1958-11-21 07:23:57');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Francisca', 'Nacci', '83708 Arapahoe Circle', 'Huntsville', 'TX', 'M', '1992-02-12 04:33:39');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Fayette', 'Killough', '609 Everett Way', 'Cumming', 'GA', 'F', '1999-07-14 07:12:33');
insert into runner (first_name, last_name, street, city, state_code, gender_code, birthday) values ('Shannen', 'Springthorp', '1 Steensland Center', 'Southfield', 'MI', 'M', '1956-04-20 20:25:09');

